### PR TITLE
Update Provider for 3.3.0

### LINKED ISSUE #48: Add DB2 iSeries extension method for LinqToDbConnectionOptionsBuilder
It makes sense to add `UseDB2iSeries(...)` extension method for `LinqToDbConnectionOptionsBuilder` fluent configuration object like we do it [here](https://github.com/linq2db/linq2db/pull/2819)

### LINKED ISSUE #50: Provider does not work with linq2db 3.3.0.
The provider fails because it does not implement the SupportedTableOptions property.

### PR DESCRIPTION
**Pull request by devinlyons**
Update provider for 3.3.0 and add configuration helper.

Closes #50, closes #48.

### CODE REVIEW

**Comment by nsarris** [comment]
Looks good, I will pull it in a new branch and setup a v3.3.0 release. I will need to sync the tests from upstream.

@devinlyons My access to an iSeries is limited these days, can you run the tests If I guid you through it?

**Comment by devinlyons** [comment]
@nsarris, I can do that. it shouldn't be a problem.

**Comment by nsarris** [comment]
I added a couple of notes on the changes here before we continue on another PR I will create from a new branch

**Comment by devinlyons** [comment]
@nsarris, I don't see your notes anywhere. I check the issues and the comments on the PR. What changes are you wanting?

**Comment by nsarris** [comment]
@devinlyons you don't have to do anything, I just added some comments here for clarity. I ported all the changes over to a new branch along with the tests from upstream. Let's continue on that PR and I'll close this one later.
