### ISSUE TITLE
Provider does not work with linq2db 3.3.0.

### ISSUE THREAD

**Issue by devinlyons** [LinqToDB4iSeries/Linq2DB4iSeries#50]
The provider fails because it does not implement the SupportedTableOptions property.

**Comment by nsarris** [comment]
@devinlyons I'm not sure when I can put work in this one, if you care to take a shot at it you basicly have to replicate the behaviour of the DB2 provider.

**Comment by devinlyons** [comment]
@nsarris, I updated the provider but I am not super confident about the results. Please take a look at my PR and let me know if you have any notes.
